locations:
    trade_button: [860, 1670]
    waiting_box: [207, 305, 900, 570]
    pokemon_to_trade_box: [300, 160, 780, 230]
    search_button: [950, 320]
    first_pokemon_name_box: [79, 666, 300, 723]
    first_pokemon: [200, 600]
    next_button_box: [475, 1460, 620, 1510]
    name_at_next_screen_box: [200, 192, 565, 278]
    next_button: [545, 1484]
    confirm_button_box: [25, 924, 250, 980]
    confirm_button: [120, 950]

    stardust_box: [330, 890, 530, 1000]

    trade_name_box: [540, 1270, 960, 1330]

    close_pokemon_button: [540, 1705]
    weight_box: [100, 1060, 340, 1190]
    height_box: [770, 1065, 980, 1190]

    second_app_position: [540, 975]

waits:
    search_button: 1
    confirm_button: 2
    close_pokemon_button: 3
    app_switch: 1
    # second_app_position: 1