locations:
    trade_button_label: [805, 1682, 987, 1760]   # the label of the trade button

    waiting_box: [218, 378, 864, 532]   # the "Waiting for NAME to connect" text
    error_box: [33, 799, 1048, 1343]   # the error boxes that can appear when trading

    # the OK button at the error boxes
    error_box_ok: [478, 1146, 610, 1226]

    pokemon_to_trade_box: [305, 150, 774, 238]
    # the POKEMON TO TRADE text after the trade begins (at the poke selector)
    # the search button in the pokemon selector
    search_button: [926, 293, 984, 342]

    # the first pokemon's position
    first_pokemon: [77, 514, 316, 712]

    # the NEXT button text after selecting a pokemon
    next_button_box: [414, 1736, 661, 1852]

    # the pokemon's name in the NEXT screen
    name_at_next_screen_box: [180, 195, 632, 298]

    trade_name_box:                 # the pokémon's name text in the final screen
    trade_name_box_no_location:     # the pokémon's name text in the final screen (when it has no location info)
    confirm_button_box:   # the CONFIRM button text in the final screen

    weight_box:    # the weight text in the pokémon's screen after the animation (the whole thing, including the height itself)
    close_pokemon_button:     # the X button for closing the pokémon screen

    # where to click to switch to the second app after the app switcher is opened
    second_app_position: [514, 999, 696, 1191]




confirm_button_box: [11, 1066, 278, 1169]

waits:
    trade_button: 2.5
    second_app_position: 1
    error_box_ok: 1
    confirm_button: 1.5
    first_pokemon: 0.7

names:
    name_check: "TRAD"    # all your trading pokémons *must* contain this string to ensure
                          #   the script doesn't trade a pokémon that wasn't intended to be traded.
    search_string: "π,Ω,μ"   # this is what gets pasted on the search box to filter which pokémons are tradeable.

    # Example:
    #   If all your pokémons for trade are named: '! TRADE', you'd use above:
    #   - name_check: "TRADE"
    #   - pokemon_search: "!"
