locations:
    trade_button: [860, 1670]                    # the trade button
    trade_button_label: [790, 1680, 1000, 1730]  # the label of the trade button

    waiting_box: [207, 305, 900, 570]  # the Waiting for NAME to connect text
    error_box: [100, 700, 1000, 1200]  # the error boxes that can appear when trading
    error_box_ok: [540, 1020]          # the OK button at the error boxes

    pokemon_to_trade_box: [300, 160, 780, 230]   # the POKEMON TO TRADE text after the trade begins (at the poke selector)
    search_button: [950, 320]                    # the search button in the pokemon selector
    first_pokemon_name_box: [79, 666, 300, 723]  # the first pokemon's name text
    first_pokemon: [200, 600]                    # the first pokemon's position

    next_button_box: [475, 1460, 620, 1510]        # the NEXT button text after selecting a pokemon
    name_at_next_screen_box: [200, 192, 565, 278]  # the pokemon's name in the NEXT screen
    next_button: [545, 1484]                       # the NEXT button

    trade_name_box: [540, 1270, 960, 1330]   # the pokémon's name text in the final screen
    confirm_button_box: [25, 924, 250, 980]  # the CONFIRM button text in the final screen
    confirm_button: [120, 950]               # the CONFIRM button

    power_up_box: [190, 1450, 470, 1540]  # the POWER UP text in the pokémon's screen after the animation
    close_pokemon_button: [540, 1705]     # the X button for closing the pokémon screen

    second_app_position: [540, 975]  # where to click to switch to the second app after the app switcher is opened

waits:
    trade_button: 1.5
    second_app_position: 0.5
    error_box_ok: 1